Support for object patches with resource-locker-operator
projectsyn/component-adhoc-configurations pull request #2
Opened 2021-03-16 15:06 UTC by simu

## Checklist

- [ ] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [ ] Update the ./CHANGELOG.md.
- [ ] Link this PR to related issues.

2021-03-17 16:26 UTC, simu commented on postprocess/resource_locker.jsonnet
> +      'adhoc-configurations-%s' % obj.metadata.name;
I'm not convinced this is the right approach. Another option would be to ignore the provided `metadata.name` and instead generate names for each ResourceLocker object based on the input filename.

2021-03-18 08:04 UTC, corvus-ch requested changes

2021-03-18 08:04 UTC, corvus-ch commented on postprocess/resource_locker.jsonnet
> +      'adhoc-configurations-%s' % obj.metadata.name;
Using the input file name can become dificult as there could me more than one ResourceLocker object in one file. Apart from that, defining an object name is something that comes natural. I would be confused if I do not have to do it.

2021-03-18 08:04 UTC, corvus-ch commented on postprocess/resource_locker.jsonnet
> +    apiVersion: 'redhatcop.redhat.io/v1alpha1',
Please make that configurable.

2021-03-18 09:42 UTC, simu commented on postprocess/resource_locker.jsonnet
> +      'adhoc-configurations-%s' % obj.metadata.name;
> Using the input file name can become dificult as there could me more than one ResourceLocker object in one file. 

This part can be handled easily enough (implementing this in Jsonnet could be another story though) by generating names of the form `adhoc-configurations-<filename>-<N>` where N is a running counter per file which gets increased for every ResourceLocker object we process.

> Apart from that, defining an object name is something that comes natural. I would be confused if I do not have to do it.

Fair enough.

2021-03-18 09:50 UTC, simu commented on postprocess/resource_locker.jsonnet
> +    apiVersion: 'redhatcop.redhat.io/v1alpha1',
I want to do a follow-up change in https://github.com/projectsyn/component-resource-locker to have that component provide the apiVersion it supports as part of its component library and use the component library here.

IMO it makes no sense to expose this value to the users, they *shouldn't* have to care about the apiVersion of the ResourceLocker objects, since we manage the operator inside the same framework (Project Syn) as the object patches.

2021-03-18 09:54 UTC, corvus-ch commented on postprocess/resource_locker.jsonnet
> +    apiVersion: 'redhatcop.redhat.io/v1alpha1',
> IMO it makes no sense to expose this value to the users, they shouldn't have to care about the apiVersion of the ResourceLocker objects […]

I agree but I know that this will become an issue sooner than later. But I like your idea of having this fetched from the resource locker component.

2021-03-19 09:09 UTC, corvus-ch approved these changes

2021-03-19 10:15 UTC, simu commented
@corvus-ch I've removed the parameter to specify a namespace for the ServiceAccount since the ServiceAccount must be in the same namespace as resource-locker-operator.

2021-03-19 12:48 UTC, corvus-ch approved these changes

2021-03-19 13:32 UTC, merged